CREATE TABLE users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(50) NOT NULL,
state VARCHAR(2) NOT NULL,
city VARCHAR(50) NOT NULL,
nick VARCHAR(10) NOT NULL,
email VARCHAR(20) NOT NULL,
password VARCHAR(50) NOT NULL,
token VARCHAR(32) NOT NULL,
date VARCHAR(50) NOT NULL
);

CREATE TABLE folders(
id INTEGER PRIMARY KEY AUTOINCREMENT,
nameFolder VARCHAR(50) NOT NULL,
idUser INTEGER NOT NULL,
FOREIGN KEY (idUser) REFERENCES users(id)
);
