CREATE TABLE users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
nomeUsuario VARCHAR(50) NOT NULL,
dataNascimento VARCHAR(10) NOT NULL,
sexo VARCHAR(20) NOT NULL,
nick VARCHAR(10) NOT NULL,
email VARCHAR(20) NOT NULL,
password VARCHAR(10) NOT NULL,
token VARCHAR(32) NOT NULL
);

CREATE TABLE folders(
id INTEGER PRIMARY KEY AUTOINCREMENT,
nomePasta VARCHAR(10) NOT NULL,
idUsuario INTEGER NOT NULL,
FOREIGN KEY (idUsuario) REFERENCES users(id)
);
