CREATE TABLE managers(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL
);

CREATE TABLE users(
nick VARCHAR(10) PRIMARY KEY,
name VARCHAR(100) NOT NULL,
country VARCHAR(100) NOT NULL,
state VARCHAR(2) NOT NULL,
city VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL,
date VARCHAR(50) NOT NULL
);

CREATE TABLE buckets(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(50) NOT NULL,
private BOOLEAN NOT NULL,
date VARCHAR(50) NOT NULL,
owner VARCHAR(10) NOT NULL,
FOREIGN KEY (owner) REFERENCES users(nick)
);